name: Release RAW

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build backend (linux amd64)
        run: |
          GOOS=linux GOARCH=amd64 go build -o ./raw/usr/bin/zimaos-cron ./cmd/zimaos-cron
          chmod +x ./raw/usr/bin/zimaos-cron

      - name: Install squashfs-tools
        run: |
          sudo apt-get update
          sudo apt-get install -y squashfs-tools

      - name: Package RAW
        run: |
          mksquashfs raw/ zimaos_cron.raw --no-append -comp xz
          ls -lh zimaos_cron.raw

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zimaos_cron.raw
          path: zimaos_cron.raw

      - name: Get version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Update release
        uses: zhanghengxin/git-release-private@ice
        with:
          token: ${{ secrets.CICD_GITHUB_TOKEN }}
          allow_override: true
          gzip: false
          tag: ${{ steps.get_version.outputs.VERSION }}
          files: ./zimaos_cron.raw
